const data = {
    products: [
      {
        title: 'Free Shirt',
        slug: 'free-shirt',
        category: 'Shirts',
        thumbnail: '/images/nanu.jpg',
        price: 70,
        brand: 'Nike',
        rating: 4.5,
        review: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        title: 'Fit Shirt',
        slug: 'fit-shirt',
        category: 'Shirts',
        thumbnail: '/images/nanu.jpg',
        price: 80,
        brand: 'Adidas',
        rating: 4.2,
        review: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        title: 'Slim Shirt',
        slug: 'slim-shirt',
        category: 'Shirts',
        thumbnail: '/images/nanu.jpg',
        marked_price: 90,
        brand: 'Raymond',
        rating: 4.5,
        review: 10,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        title: 'Golf Pants',
        slug: 'golfpant',
        category: 'Pants',
        thumbnail: '/images/nanu.jpg',
        marked_price: 90,
        brand: 'Oliver',
        rating: 4.5,
        review: 10,
        countInStock: 20,
        description: 'Smart looking pants',
      },
      {
        title: 'Fit Pants',
        category: 'Pants',
        thumbnail: '/images/nanu.jpg',
        price: 95,
        brand: 'Zara',
        rating: 4.5,
        review: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
      {
        title: 'Classic Pants',
        category: 'Pants',
        thumbnail: '/images/nanu.jpg',
        price: 75,
        brand: 'Casely',
        rating: 4.5,
        review: 10,
        countInStock: 20,
        description: 'A popular pants',
      },
    ],
    // apiHost:'http://127.0.0.1:8000',
    apiHost: 'http://nanu.gyannhub.com'
  };
  export default data;